cookie:
  expiry_days: 7
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    heechan12:
      name: "\uC591\uD76C\uCC2C"
      password: $2b$12$ozQWNSx3HOvgRJKup2IDxO7kC6SByrYL5mmrXQmGPy29j3OvGPSXK
    yediz:
      name: "\uAE40\uC608\uC9C0"
      password: $2b$12$qzLwGb0GlhjR0XXo8i8EKOcnTQcTI5RufQj8K5TlayFzCo83ieIaW
preauthorized:
  emails:
  - test@example.com
